site_name: 青少年CTF文库
site_url: https://docs.qsnctf.com
site_description: 适合你快速入门的CTF百科全书
theme:
  name: material
  language: zh # 中文模式
  logo: assets/logo.png
  favicon: assets/logo.png
  # 主题配色
  palette:
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  # 字体配置        
  font:
    text: Noto Sans
    code: Source Code Pro
  # 图标
  icon:
    repo: simple/github
  features:
    - content.action.edit # 编辑按钮
    - content.action.view # 查看按钮
    - content.code.annotate # 代码注释
    - content.code.copy # 复制代码
    - content.tabs.link # 标签链接
    - content.tooltips  # 工具提示
    - navigation.indexes # 导航索引
    - navigation.instant # 即时加载
    - navigation.tabs # 导航标签
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 指示进度器
    - navigation.tracking # 锚点跟踪
    - navigation.path # 面包屑导航
    - navigation.top # 导航顶部
    - navigation.tracking # 导航跟踪
    - toc.follow # 目录跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索分享

    
# repo
repo_url: https://github.com/qsnctf/qsnctf.github.io
repo_name: qsnctf/qsnctf.github.io
edit_uri: edit/docs/docs/

# plugins
plugins:
  # - git-committers: # 贡献人
  #     repository: qsnctf/qsnctf.github.io
  #     branch: main
  # - git-authors # 展示作者
  - search # 内置搜索
  - tags # 标签
  - markmap # 思维导图


docs_dir: docs
site_dir: site

extra:
  generator: false
  social:
    - icon: simple/qq
      link: https://qm.qq.com/q/Ibz8EXRckO
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2066710972
    - icon: fontawesome/brands/github
      link: https://github.com/qsnctf    
    - icon: fontawesome/solid/paper-plane
      link: mailto:lqn@sierting.com

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js




copyright: Copyright 青少年CTF &copy; 2025 版权所有

extra_css:
  - stylesheets/markmap.css
  - stylesheets/main.css
  
# markdown 拓展
markdown_extensions:
# 详细参考 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr # 添加词汇表 https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary 添加缩写: https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations
  - admonition # 警告 https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      #linenums: true # 显示行号
      #auto_title: true # 显示编程语言名称
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify

# nav
nav:
  - 首页: index.html
  - 起始页: 
    - 起始页: home.md
    - 知识树: Knowledge_Tree.md
  - 基础知识:
    - 什么是 CTF: basic/intro.md
    - CTF的历史: basic/history.md
    - 练习CTF: basic/practice.md
    - 计算机基础: 
      - 计算机是怎么工作的？: basic/How_does_a_computer_work.md
      - 操作系统: basic/operating_system.md
    - 计算机网络:
      - 网络基础: basic/network/intro.md
      - OSI七层模型: basic/network/osi.md
  - 编程: 
    - 介绍: Code/index.md
    - C/C++: 
      - C/C++介绍: Code/CPP/cpp-tutorial.md
      - C++基本语法: Code/CPP/cpp-basic-syntax.md
      - C++注释: Code/CPP/cpp-comments.md
      - C++数据类型: Code/CPP/cpp-data-types.md
      - C++变量类型: Code/CPP/cpp-variable-types.md
      - C++变量作用域: Code/CPP/cpp-variable-scope.md
      - C++常量: Code/CPP/cpp-constants-literals.md
    - 汇编语言: 
      - 汇编语言概述: Code/Assembly/Language_Overview.md
      - 基础环境与工具: Code/Assembly/Basic_Environment_and_Tools.md
      - 计算机底层基础: Code/Assembly/Computer_Low-Level_Fundamentals.md
      - 寄存器: Code/Assembly/Registers.md
      - 内存与栈: Code/Assembly/Memory_and_Stack.md
      - 指令系统: Code/Assembly/Instruction_Set.md
      - 控制流: Code/Assembly/Control_Flow.md
      - 函数与调用约定: Code/Assembly/Functions_and_Calling_Conventions.md
      - 数据与变量: Code/Assembly/Data_and_Variables.md
      - 常见体系结构: Code/Assembly/Common_Architectures.md
      - 汇编与高级语言的关系: Code/Assembly/Relationship_Between_Assembly_and_High-Level_Languages.md
      - 汇编调试与分析: Code/Assembly/Assembly_Debugging_and_Analysis.md
      - 汇编在CTF中的应用: Code/Assembly/Assembly_in_CTF.md
    - Python:
      - Python介绍: Code/Python/Python_Intro.md
      - Python基础语法: Code/Python/Python_Basic_Syntax.md
      - Python数据类型: Code/Python/Python_Data_Type.md
      - Python类型转换: Code/Python/Python_Type_Conversion.md
      - Python注释: Code/Python/Python_Comment.md
      - Python运算符: Code/Python/Python_Basic_Operators.md
      - Python条件控制: Code/Python/Python_Conditional_Statements.md
      - Python循环控制: Code/Python/Python_Loop.md
      - Python推导式: Code/Python/Python_Comprehensions.md
      - Python迭代器生成器: Code/Python/Python_Iterator-Generator.md
      - Python-With: Code/Python/Python_With.md
      - Python函数: Code/Python/Python_Functions.md
      - Python Lambda: Code/Python/Python_lambda.md
      - Python 装饰器: Code/Python/Python_Decorators.md
      - Python 数据结构: Code/Python/Python_Data_Structure.md
      - Python模块: Code/Python/Python_module.md
      - Python内置变量: Code/Python/Python_Internal_Variable.md
      - Python文件操作: Code/Python/Python_File.md
      - Python OS: Code/Python/Python_OS.md
      - Python错误和异常处理: Code/Python/Python_Errors_Execptions.md
      - Python面向对象: Code/Python/Python_Class.md
      - Python命名空间/作用域: Code/Python/Python_Namespace_Scope.md
      - Python虚拟环境: Code/Python/Python_Venv.md
      - Python标准库: Code/Python/Python_stdlib.md
      - Python类型注解: Code/Python/Python_Type_Hints.md
    - PHP: Code/PHP.md
  - Misc: 
    - 介绍: Misc/index.md
    - 编码:
      - ASCII: Misc/encoding/ASCII.md
      - Hex: Misc/encoding/Hex.md
      - Base家族:
        - Base64: Misc/encoding/Base/Base64.md
        - Base32: Misc/encoding/Base/Base32.md
        - Base36: Misc/encoding/Base/Base36.md
        - Base58: Misc/encoding/Base/Base58.md
    - 文件结构:
      - 各种文件的结构: 
        - PNG: Misc/File_Structure/File_Structure/PNG_Structure.md
        - JPG: Misc/File_Structure/File_Structure/JPG_Structure.md
        - ZIP: Misc/File_Structure/File_Structure/ZIP_Structure.md
        - GIF: Misc/File_Structure/File_Structure/GIF_Structure.md
        - WAV: Misc/File_Structure/File_Structure/WAV_Structure.md
        - MP3: Misc/File_Structure/File_Structure/MP3_Structure.md
    - 文件修复:
        - PNG: Misc/File_Repair/PNG_Repair.md
        - JPG: Misc/File_Repair/JPG_Repair.md
        - ZIP: Misc/File_Repair/ZIP_Repair.md
    - 隐写术:
        - PNG: Misc/Steganography/PNG_Steganography.md
        - JPG: Misc/Steganography/JPG_Steganography.md
        - BMP: Misc/Steganography/BMP_Steganography.md
        - WAV: Misc/Steganography/WAV_Steganography.md
  - Crypto: 
    - 介绍: Crypto/index.md
    - 古典密码:
      - 单表替换:
        - 凯撒密码: Crypto/Classical_Cryptography/Single_Table_Replacement/Caesar.md
        - 埃特巴什码: Crypto/Classical_Cryptography/Single_Table_Replacement/Atbash.md
        - ROT5/13/18/47: Crypto/Classical_Cryptography/Single_Table_Replacement/ROT.md
      - 多表替换:
        - Playfair密码: Crypto/Classical_Cryptography/Multi_table_replacement/Playfair.md
        - HILL密码: Crypto/Classical_Cryptography/Multi_table_replacement/HILL.md
        - 维吉尼亚密码: Crypto/Classical_Cryptography/Multi_table_replacement/Vigen.md
      - 其他密码:
        - 培根密码: Crypto/Other_Cryptography/Baconian.md
        - 栅栏密码: Crypto/Other_Cryptography/Fence.md
        - 波利比奥斯（Polybius）方阵密码: Crypto/Other_Cryptography/Polybius_Square.md
    - 图形密码:
      - 介绍: Crypto/Graphic_Cryptography/Introduction.md
      - 猪圈密码: Crypto/Graphic_Cryptography/Piggy_Bank.md
    - 现代密码:
      - 非对称加密: 
        - RSA:
          - RSA介绍: Crypto/Modern_Cryptography/asymmetric/Introd_RSA.md
          - RSA秘钥生成: Crypto/Modern_Cryptography/asymmetric/RSA_Key_Generation.md
          - RSA加密解密: Crypto/Modern_Cryptography/asymmetric/RSA_Encryption_Decryption.md
          - RSA加解密示例: Crypto/Modern_Cryptography/asymmetric/RSA_Encryption_Decryption_Example.md
          - RSA正确性证明: Crypto/Modern_Cryptography/asymmetric/RSA_Correctness_Proof.md
  - Web: 
    - 介绍: Web/index.md
    - 基础知识:
      - 网站的工作原理 : Web/Introduction/Website_How_It_Works.md
      - 网站的状态管理: Web/Introduction/Website_Status_Management.md
    - Web基础漏洞:
      - 跨站脚本攻击(XSS):
        - XSS原理: Web/Web_Security_Basic_Vulnerabilities/Cross_Site_Scripting.md
        - XSS-LAB: Web/Web_Security_Basic_Vulnerabilities/XSS_LAB/XSS_LAB.md
  - Reverse: 
    - 介绍: Reverse/index.md
    - 工具:
      - IDA Pro: Reverse/Tools/IDA_PRO/IDA_PRO.md
  - Pwn: 
    - 介绍: Pwn/index.md
  - AI:
    - 介绍: AI/index.md
    - 环境准备: AI/Environmental/Environmental_preparation.md
    - 基础知识1: AI/Basic/Basic_knowledge.md
    - 基础知识2: AI/Basic/Basic_knowledge_2.md
  - 工具: 
    - 介绍: Tools/index.md
    - 编码工具:
      - CyberChef: Tools/encoding/CyberChef.md
  - 关于: 
    - 介绍: about.md
